version: '3.4'

services:
  blogwebapi:
    image: ${DOCKER_REGISTRY-}blogwebapi
    build:
      context: .
      dockerfile: BlogWebApi/Dockerfile
    ports:
    - 51944:8080
        
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cretPassword!123
      - POSTGRES_USER=onion_user
      - POSTGRES_DB=onion_architecture_db
  mail:
    image: rnwood/smtp4dev
    restart: always
    ports:
    - 25:25
    # environment:
    #   RELAY_HOST: smtp.blogpost.com
    #   RELAY_PORT: 587
    #   RELAY_USERNAME: alice@example.com
    #   RELAY_PASSWORD: secretpassword
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - ./seq-data:/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Jaeger UDP
    environment:
      - LOG_LEVEL=debug
volumes:
  cache:
    driver: local